name: my-github-actions
run-name: CI/CD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Requirements
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          pip3 install -r requirements.txt
      - name: CI
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          sam build
          sam validate         
      - name: Deploy stack
        run: |
          export AWS_DEFAULT_REGION='ap-southeast-2'
          bash bin/local_run.sh
      # awslocal cloudformation create-stack --stack-name  my-stack --template-body file://./template.yaml --region ap-southeast-2
      # - name: Sleep for 30 seconds
      #   run: sleep 30s
      #   shell: bash
      # - name: Invoke Lambda
      #   run: |
      #     export AWS_DEFAULT_REGION='ap-southeast-2'
      #     function_name=$(awslocal lambda list-functions --region $AWS_DEFAULT_REGION | jq -r '.Functions[] | select(.Handler=="app.app") | .FunctionName')
      #     awslocal lambda invoke --function-name $function_name --invocation-type RequestResponse --payload fileb://event.json  response.txt --region $AWS_DEFAULT_REGION
      # - name: cfn guard
      #   uses: grolston/guard-action@main # https://github.com/grolston/guard-action
      #   with:
      #     data_directory: './' ## change to your template directory
      #     rule_set: "FedRAMP-Moderate"